name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0'  # Every Sunday at 2 AM

jobs:
  benchmarks:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y time bc
        chmod +x benchmarks/*.sh
        chmod +x utils/*.sh

    - name: Run memory usage benchmarks
      run: |
        echo "📊 Running memory usage benchmarks..."
        cd benchmarks
        ./memory_usage_test.sh

    - name: Run performance benchmarks
      run: |
        echo "⚡ Running performance benchmarks..."
        cd benchmarks
        ./compare_implementations.sh

    - name: Run stress tests
      run: |
        echo "🔥 Running stress tests..."
        cd benchmarks
        ./stress_test.sh

    - name: Generate benchmark report
      run: |
        echo "📈 Generating benchmark report..."
        cd benchmarks
        ./benchmark_runner.sh --format=markdown > benchmark-report.md

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          benchmarks/results/
          benchmark-report.md
        retention-days: 30

    - name: Comment on PR with benchmarks
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('benchmark-report.md')) {
            const report = fs.readFileSync('benchmark-report.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📊 Benchmark Results\n\n${report}`
            });
          }